routeinfo/config/routes.rb
Rails.application.routes.draw do
  root to: 'search#index'

  match 'search', to: "search#search", via: [:get, :post], as: :search

  resources :routes
  resources :nodes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

routeinfo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

routeinfo/app/models/route.rb
class Route < ApplicationRecord
end

routeinfo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

routeinfo/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index                   # nutzt per Konvention den View search/index.html...
    @search = OpenStruct.new  # die Weitergabe von Daten an das View erfolgt
                              # über Instance-Attribute
  end

  def search
    @search = OpenStruct.new params[:search]
    logger.debug "Start search with: #{@search.to_json}"
    if (@search.source =~ /^a/i)
      @route = OpenStruct.new(:source => @search.source,
                              :vertexes => ['Hannover', 'Berlin'],
                              :destination => @search.destination,
                              :distance => 560)
    else
      @route = :not_found
    end
    render :action => :index
  end
end

routeinfo/app/helpers/application_helper.rb
module ApplicationHelper

  # Formatieren einer Zahl (Tausender-Trenner) und anhängen der Einheit "km"
  # Parameter:
  #   distance:  Distance als ganze Zahl (darf nil sein)
  # Returns:
  #   String mit der formatierten Distance (bei nil => leerer String)
  def format_km distance
    return "" if distance.nil?
    number_with_delimiter(distance, :separator => ".")+" km"
  end


end

routeinfo/app/helpers/search_helper.rb
module SearchHelper
end

routeinfo/app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Route-Info-System
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application", 'data-turbolinks-track': 'reload'
    = csrf_meta_tags
    = csp_meta_tag
  %body
    %h1 Route-Info-System
    = yield

routeinfo/app/views/search/index.html.haml
%h2 Suche Verbindung

= form_for @search, :as => :search, :url => search_path do |f|
  = f.label 'Von '
  = f.text_field :source
  = f.label 'Nach '
  = f.text_field :destination
  = submit_tag 'suche'

- if @route
  .result
    - if @route == :not_found
      %p Leider nichts gefunden
    - else
      %h3 Ergebnis:
      = render partial: 'route', object: @route